sudo:
  false

language:
  python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  - pip install --upgrade -r requirements.dev.txt

script:
  - python -m mario.cli check

after_success:
  - python -m mario.cli report

deploy:
  provider: pypi
  user: roll
  password:
    secure: EtPOQV6AoJUbSlFX4C84zP9KK46BUzjy8IcXwfviNiieyfUsO3S4zs4N4PSTKBjQCJudCXU6+kRQlQV0WBbT80cr4IQVKGV+KqysK5NabytzXHEXUHci/vGhPwzhWv7bGNDMUdwp3FoWqbYT8AYpNXkHFOuZRIr3r4O3I++YjkwSednqt3U7822eFuNfujpsO6A6CRIdhzzQ3bfXtyEtQd1M17lUv1WyRrV0DgXtYvnkzm5M0I6h6h861iXLkPgW1DMLn4vIeouj/txzzhs0HlYyZFsDRdvAaNPTI0o63VGXJ81LExHUa4fVYasW1IGyzABT9dBEENc0LiF7035QkwSHgEfVzieQ0OcuEmVsBMB0uVGupCprus9dgX1zZCBx/SE+4WxXKZ+/R6OGOcIVlKYVsCtZnFv7aYLWN9Z0hzE9tlESXwM6/4VbEV9lVtOzsVjT7ePZ0+nmR63hcrmfPUdL3ec1crGoNvWmY2JmmjDWvke11qyMw/XmHohPVByc9RwwX/i/EuF0+Jj4OY7p3mOZMrnk8a/H01ifuXVj/HfIQuY5i1bILS8lny6E6QGugG9CkcRPRQSLzLg0stR6LVlmdy1wUMqwSpcMq6YzWaUj+pdOT6HkPA7GkmpfNjTI9Pkn6MNo7TwOjZFiglQHAMwriz3rfyR4f5iDFAb/J38=
  on:
    tags: true
